on:
  push:
    branches: [master]

jobs:
  gofmt&lint:
    runs-on: ubuntu-latest
    steps: 
    - name: checkout
    - uses: actions/checkout@v2

    - name: gofmt
      run: if [ $(gofmt -l -s . | wc -l) -ne 0 ]; then echo "fmt failed"; exit 1; fi

    - name: golint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.29
        only-new-issue: true
